/*
 * generated by Xtext
 */
package de.wwu.pi.acse.crudDslXX.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CrudDslXXUiModule extends de.wwu.pi.acse.crudDslXX.ui.AbstractCrudDslXXUiModule {
	public CrudDslXXUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
