/*
 * generated by Xtext
 */
package de.wwu.pi.acse.crudDslXX;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CrudDslXXRuntimeModule extends de.wwu.pi.acse.crudDslXX.AbstractCrudDslXXRuntimeModule {

}
