/*
 * generated by Xtext
 */
package de.wwu.pi.acse.crudDslXX;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CrudDslXXStandaloneSetup extends CrudDslXXStandaloneSetupGenerated{

	public static void doSetup() {
		new CrudDslXXStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

