/*
 * generated by Xtext
 */
package de.wwu.pi.acse.crudDslXX;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class CrudDslXXUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return de.wwu.pi.acse.crudDslXX.ui.internal.CrudDslXXActivator.getInstance().getInjector("de.wwu.pi.acse.crudDslXX.CrudDslXX");
	}
	
}
